### ISSUE TITLE
Database Column Error

### ISSUE THREAD

**Issue by gotspatel** [palinkas-jo-reggelt/hMailServer_pURIBL#1]
Hi Palinka,

Can you help here. Getting below error for both tables,

Error Code: 1170
BLOB/TEXT column 'uri' used in key specification without a key length

Error Code: 1170
BLOB/TEXT column 'domain' used in key specification without a key length

It says the text column cannot be used as unique [HERE](https://stackoverflow.com/a/1827099)

Can/should the column be set to varchar(254) ?

**Comment by palinkas-jo-reggelt** [comment]
I just dumped the table structure to make sure it matches what I posted and it does:

```
CREATE TABLE hm_puribluri (
  id int(11) NOT NULL AUTO_INCREMENT,
  uri text NOT NULL,
  domain varchar(128) NOT NULL,
  timestamp datetime NOT NULL,
  adds mediumint(9) NOT NULL,
  hits mediumint(9) NOT NULL,
  active tinyint(1) NOT NULL,
  ADD PRIMARY KEY (id),
  ADD UNIQUE KEY uri (uri) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

Are you USING HASH for the key? I'm not an expert at that. When I created the key in phpmyadmin, USING HASH was automatically added.

**Comment by gotspatel** [comment]
> Are you USING HASH for the key? I'm not an expert at that.

Sorry Don't know anything about it. will investigate and inform you


> When I created the key in phpmyadmin,

This also I don't know, will have to check.

**Comment by palinkas-jo-reggelt** [comment]
The hash length is much smaller (32 char???) and fixed, so the error should not be thrown when USING HASH on unique key.

**Comment by gotspatel** [comment]
I changed this

UNIQUE KEY uri (uri) USING HASH

To this

UNIQUE uri (**uri(255)**) USING HASH

The table created successfully. But got a message 

Note Code : 3502
This storage engine does not support the HASH index algorithm, storage engine default was used instead.

I am using MYSQL DB version 8.0,

Don't know if it is correct way or not.

**Comment by palinkas-jo-reggelt** [comment]
> Note Code : 3502 This storage engine does not support the HASH index algorithm, storage engine default was used instead.

Are you using innodb?

I'm using mariadb, but I don't think there should be much of a difference.

**Comment by gotspatel** [comment]
Yes I am using innodb.

it seems that mysql innodb doesn't have hash algorithm by itself. as it is in mariadb.

waiting for a hit to check if the above table change is working or not.

**Comment by palinkas-jo-reggelt** [comment]
Try the test script located in the events folder. At the bottom, uncomment the calls to execute sql.
```
' Call oDB.ExecuteSQL(strSQL)
```

**Comment by gotspatel** [comment]
Field 'hits' doesn't have a default value.

so I changed the query lines as the table has hits as **notnull**

strSQL = "INSERT INTO " & pURIBLURITable & " (uri,domain,timestamp,adds,**hits**,active) VALUES ('" & Match.SubMatches(0) & "','" & GetMainDomain(MatchD.SubMatches(0)) & "',NOW(),1,**0**,1) ON DUPLICATE KEY UPDATE adds=(adds+1),timestamp=NOW();"

strSQLD = "INSERT INTO " & pURIBLDomTable & " (domain,timestamp,adds,**hits**,shortcircuit) VALUES ('" & GetMainDomain(MatchD.SubMatches(0)) & "',NOW(),1,**0**,1) ON DUPLICATE KEY UPDATE adds=(adds+1),timestamp=NOW();"

the database is populated with the data and it works

**Comment by palinkas-jo-reggelt** [comment]
Ok great. I'll update the test script to fix that bug.

**Comment by gotspatel** [comment]
please note the same applies to the code which goes into eventhandler.vbs
